USE sakila;

SELECT *
FROM ACTOR, FILM, CUSTOMER;

SELECT FILM.TITLE
FROM FILM;

SELECT DISTINCT NAME
FROM LANGUAGE;

SELECT STAFF.FIRST_NAME, STAFF.LAST_NAME
FROM STAFF;

SELECT DISTINCT RELEASE_YEAR
FROM FILM;

SELECT COUNT(STORE_ID) AS N_STORES
FROM STORE;

SELECT COUNT(STAFF_ID) AS N_EMPLOYEES
FROM STAFF;

NUMERO DE PELICULAS DISPONIBLES Y NYUMERO DE PELICULAS ALQUILADAS

SELECT COUNT(DISTINCT LAST_NAME) AS N_LASTNAME_ACTORS
FROM ACTOR;

SELECT TITLE, LENGTH
FROM FILM
ORDER BY LENGTH DESC
LIMIT 10;

SELECT FIRST_NAME, LAST_NAME
FROM ACTOR
WHERE FIRST_NAME = 'SCARLETT';

SELECT TITLE, LENGTH
FROM FILM
WHERE (TITLE = 'ARMAGEDDON') AND (LENGTH > 100);

SELECT DISTINCT SPECIAL_FEATURES
FROM FILM;

SELECT TITLE, SPECIAL_FEATURES
FROM FILM
WHERE SPECIAL_FEATURES LIKE 'Behind the Scenes';

